name: Update-CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 14 * * 0
  #watch:
  #  types: [started]
  #push:
  #  branches: 
  #    - master
      
jobs:
  build:

    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@master
    
    - name: update serverlist
      run: | 
        rm -Rf *
        git rm --cache *
        wget 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=0&mimetype=plaintext' -nv -O ./yoyo.txt
        wget -qO - 'https://github.com/VeleSila/yhosts/raw/master/hosts' |  grep 0.0.0.0 > ./chn.txt
        sed -i 's,0.0.0.0 ,,g' ./chn.txt
        sed -i '/#/d' ./chn.txt
        cat ./chn.txt ./yoyo.txt | sort | uniq > ./serverlist.txt
        cat ./serverlist.txt | while read line
        do
          echo "address /$line/#" >> ./serverlist.conf
          echo "||$line^" >> ./adfilter_adguarhome.txt
        done
        rm -f ./yoyo.txt
        rm -f ./chn.txt
        rm -f ./serverlist.txt


    - name: update gfwlist
      run: | 
        wget -O ./gfwlist.sh 'https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh'
        sh gfwlist.sh -l -o gfwlist_domain.txt
        cat ./gfwlist_domain.txt | while read line
        do
          echo "nameserver /$line/oversea" >> ./gfwlist.conf
        done
        rm -f ./gfwlist_domain.txt
        rm -f ./gfwlist.sh


        
    - name: update china-domain-list
      run: | 
        wget -O ./china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        wget -O ./apple.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        wget -O ./google.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf

        #合并
        cat ./apple.conf >> ./china.conf 2>/dev/null
        cat ./google.conf >> ./china.conf 2>/dev/null
        cp ./china.conf ./adguardhome-China.txt

        #删除不符合规则的域名
        sed -i "s/^server=\/\(.*\)\/[^\/]*$/nameserver \/\1\/china/g;/^nameserver/!d" ./china.conf 2>/dev/null
        sed -i "s/^server=\/\(.*\)\/[^\/]*$/[\/\1\/]192.168.31.5:6053/g;/^[/!d" ./adguardhome-China.txt 2>/dev/null
        
        rm -f ./apple.conf
        rm -f ./google.conf

        
        
        
    - name: Commit file
      run: |
        git config --global user.email ow4867208@gmail.com
        git config --global user.name kiligone
        sudo timedatectl set-timezone "Asia/Shanghai"
        git add .
        git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a || true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.REPO_TOKEN}}
        
    - name: Cleanup Workflow Logs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
